In [1]:
import tensorflow as tf

x1 = tf.constant(5)  # Definition of the first constant: 5
x2 = tf.constant(10)  # Definition of the second constant: 10

print(x1)  # Display the first constant
print(x2)  # Display the second constant

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)




| NumPy Operation           | TensorFlow Operation   |
|---------------------------|------------------------|
| `np.add` or `+`           | `tf.add` or `+`        |
| `np.subtract` or `-`      | `tf.subtract` or `-`   |
| `np.matmul`               | `tf.matmul`            |
| `np.transpose`            | `tf.transpose`         |
| `np.linalg.inv`           | `tf.linalg.inv`        |
| `np.cos`                  | `tf.cos`               |
| `np.sin`                  | `tf.sin`               |
| `np.tan`                  | `tf.tan`               |
| `np.log`                  | `tf.log`               |
| `np.exp`                  | `tf.exp`               |
| `np.reshape`              | `tf.reshape`           |
| `np.concatenate`          | `tf.concat`            |
| `np.expand_dims`          | `tf.expand_dims`       |
| `np.arange`               | `tf.range`             |


In [10]:
result = tf.add(x1, x2)  # Call the add function to add x1 and x2
# Equivalent solution :
# result = x1 + x2

print(result)  # Display the result
print(result.numpy())

tf.Tensor(15, shape=(), dtype=int32)
15


In [ ]:
import tensorflow as tf
import numpy as np

# Creation of a 5x10 matrix filled with zeros
X = tf.zeros(shape = (5, 10))
# Creation of a 3 dimensional matrix 3x10x10 filled with ones
X = np.ones(shape = (3, 10, 10))

In [ ]:
X = tf.constant([2*i for i in range(10)])    # 0, 2, 4, 6, ..., 18
# Creation of a tensor from an array.
X = np.array([[1, 3, 3],
             [3, 3, 1],
             [1, 2, 0]])
X = tf.constant(X)

| NumPy Function       | TensorFlow Equivalent   |
|----------------------|-------------------------|
| `np.zeros`           | `tf.zeros`              |
| `np.ones`            | `tf.ones`               |
| `np.eye`             | `tf.eye`                |
| `np.transpose`       | `tf.transpose`          |
| `np.random.normal`   | `tf.random.normal`      |
| `np.random.uniform`  | `tf.random.uniform`     |


In [18]:
X = tf.random.uniform([10000, 2])
print('Min of X :', tf.reduce_min(X).numpy())
print('Max of X :', tf.reduce_max(X).numpy())
print(X)

Min of X : 2.3841858e-06
Max of X : 0.99996984
tf.Tensor(
[[0.654191   0.05673862]
 [0.34173644 0.6819817 ]
 [0.5045128  0.64118016]
 ...
 [0.15361953 0.10590267]
 [0.843711   0.12636685]
 [0.16032565 0.88329625]], shape=(10000, 2), dtype=float32)


In [19]:
import tensorflow as tf
X = tf.zeros(shape = (10, 10))
## display of the element in the index (4, 3)
print(X[4, 3])

tf.Tensor(0.0, shape=(), dtype=float32)


In [20]:
X = tf.zeros(shape = (4, 5))
## displays a sub-matrix of X
print(X[1:4, 2:5])

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
